Install numpy before pandas
Suggested workaround for when installing pandas
```
RuntimeError: Python version >= 3.5 required.
```
https://github.com/pandas-dev/pandas/issues/27159#issuecomment-507262035